n<-as.integer(readline("enter number of employees"))
empid<-vector(mode="character",length = n)
empname<-vector(mode="character",length = n)
empdesig<-vector(mode="character",length = n)
empdept<-vector(mode="character",length = n)
print("enetr all the details")
for(i in 1:n)
  empid[i]<-readline("enter the empid")
for(i in 1:n)
  empname[i]<-readline("enter the empname")
for(i in 1:n)
  empdept[i]<-readline("enter the empdept")
for(i in 1:n)
  empdesig[i]<-readline("enter the empdesig")
employees<-data.frame(empid,empname,empdept,empdesig)
print(employees)
write.csv(employees,"uzmanew.csv")
datafromcsv=read.csv("uzmanew.csv")
print("printing from csv file")
print(datafromcsv)
newrow=data.frame("111","hhhh","aero","newinteren2")
write.table(newrow,"uzmanew.csv",append = TRUE,col.names = FALSE,row.names = TRUE,sep = " , ")
datafromcsv=read.csv("uzmanew.csv")
print("printing from csv new file")
print(datafromcsv)